# Run eslint
name: Run Eslint in frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Packages
        run: npm ci

      - name: Lint Code Base
        run: npm run lint
