# Run eslint
name: Run Eslint in backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run: working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

#       - name: Go to backend dir
#         run: cd backend

      - name: Install Packages
        run: npm ci

      - name: Lint Code Base
        run: npm run lint
