# Run npm check
name: npm-check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Packages
        run: npm ci
