# Run all tests
name: Run Tests on frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-tests-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Go to frontend
        run: cd frontend

      - name: Install Packages
        run: npm ci

      - name: Run all tests
        run: npm run test
